version : "3"
services :
    bot :
        container_name: "pathetic-geek_bot"
        build: 
            context: .
            dockerfile: "./Dockerfile"
        env_file: "./.env"
        restart: always
