name: Deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Staging Master Node
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SECRET }}
          port: 22
          script: |
            cd pathetic-geek_bot
            git pull origin master
            git status
            docker-compose down
            docker-compose build
            docker-compose up -d
